CodeForAfrica/HURUmap-UI

package.json
src/MapIt/index.tsx
src/MapIt/useDeepRef.ts
stories/mapit.stories.tsx
yarn.lock

Fix issues with too many reloads that cost a lot of data and glitchy ui.

Fix mapit too many reloads 

---

src/NumberVisuals/index.tsx
src/Theme.ts
src/index.ts
stories/numbers.stories.tsx

Add number visual card

---

src/BarChart.js
src/BulletChart/BulletBar.js
src/BulletChart/index.js
src/Chart.js
src/ComparisonBarChart.js
src/CustomContainer.js
src/LineChart.js
src/NestedProportionalAreaChart/HorizontalLegend.js
src/NestedProportionalAreaChart/ScaledCircle.js
src/NestedProportionalAreaChart/ScaledSquare.js
src/NestedProportionalAreaChart/VerticalLegend.js
src/NumberVisuals.js
src/PieChart/index.js
src/WrapLabel/index.js
stories/chart.stories.js

Fix tickFormat & PropTypes

---

src/ChartContainer/EmbedDropDown.js
src/ChartContainer/ShareDropDown.js
src/ChartContainer/index.js
src/InsightContainer/Actions.js
src/InsightContainer/index.js
stories/container.stories.js

Custom props for chart containers

---

src/InsightContainer/Actions.js
src/InsightContainer/index.js
src/NumberVisuals.js
stories/container.stories.js
stories/numbers.stories.js

Style config + undefined props update

---

package.json
src/ChartContainer/ShareDropDown.js
src/ChartContainer/index.js
stories/container.stories.js
yarn.lock

Enable sharing of HURUmap-UI chart cards via social media. By default, `window.location.href` will be shared if no other URL is supplied.

Improve Share Dialog

---

src/ChartContainer/index.js
src/MapIt/index.js
src/PieChart/index.js
stories/container.stories.js

v0.1.11 Improvements

---

.eslintrc.js
src/InsightContainer/Actions.js
src/InsightContainer/Insight.js
src/InsightContainer/index.js
stories/container.stories.js

Reusable Insight Chart Container

---

src/factory/ChartFactory.js
stories/factory.stories.js

Fix issues where prop spreading would override computed properties.

Fix Chartfactory

---

src/core/InsightContainer/Insight.js
src/core/InsightContainer/index.js

makeStyles require func at style rule or css property level: https://material-ui.com/styles/basics/#adapting-based-on-props

[Hotfix] makeStyles variant check

---

src/core/InsightContainer/Action/ActionButton.js
src/core/InsightContainer/Action/EmbedCodeTextArea.js
src/core/InsightContainer/Action/index.js
src/core/InsightContainer/Insight.js
src/core/InsightContainer/index.js
src/core/NumberVisuals.js
src/factory/ChartFactory.js
src/factory/utils/aggregateData.js
stories/container.stories.js

~No~ flex zone.
I thought of using material ui `Box` but css is not terrible.
- Fixes the responsive issues of the InsightContainer.
- Improve data variant
- Better wrapping
- Use chart factory for story

Flex to resolve responsive issues 

---

src/core/ChartContainer/index.js

DownThemAll!

---

src/core/InsightContainer/index.js

Fix variant styles

---

src/core/Label.js
src/core/LegendLabel.js
src/core/PieChart/DonutTooltip.js
src/core/PieChart/SharedEvents.js
src/core/PieChart/index.js
src/core/styles/createVictoryTheme.js
src/core/utils.js
src/factory/ChartFactory.js
stories/chart.stories.js
yarn.lock

* e.g. https://github.com/FormidableLabs/victory/pull/1423

[Hotfix] Data Format & Tooltip

---

src/core/index.js
src/factory/utils/aggregateData.js
stories/chart.stories.js
stories/container.stories.js

[Hotfix] Stubbon @material-ui/styles reference

---

package.json
src/core/ChartContainer/index.js
src/core/InsightContainer/index.js
stories/container.stories.js
yarn.lock

Fixes  [#169749138](https://www.pivotaltracker.com/story/show/169749138)

Add forgotten chart description to insight chart container

---

.babelrc
package.json
src/core/ChartContainer/index.js
src/core/InsightContainer/Action/index.js
yarn.lock

Currently we don't do any SVG processing. This leaves it app to the downstream apps to do the processing by adding transpilling steps, etc., which are error prone.
This PR transforms imports of SVG files into React Components

[Hotfix] SVG Components

---

src/core/countries.js
src/core/index.js
stories/mapit.stories.js
yarn.lock

[Chrore] Move countries into  HURUmap UI

---

src/factory/ChartFactory.js
stories/factory.stories.js
yarn.lock

While it makes sense for size limited designs such as Takwimu, the button is not so useful in spacious designs such as Dominion & PesaYetu. Hence:
--------------------

Make SHOW MORE/SHOW LESS button optional

---

src/factory/useProfileLoader/index.js
src/factory/useProfileLoader/queries.js
src/factory/useProfileLoader/visualLoader.js
src/factory/utils/index.js
src/factory/utils/visualLoader.js
yarn.lock

Currently charts' visual data can only together with a certain `geoId` profile. This PR creates a different visual-loader function that can be used on components such as featured data or embed charts

Refactor Profile Loader

---

src/factory/ChartFactory.js

Reverts CodeForAfrica/HURUmap-UI#97

Revert Theme proptypes on chartfactory"

---

src/core/ActionsModal/DownloadPanel.js
src/core/ActionsModal/EmbedPanel.js
src/core/ActionsModal/SharePanel.js
src/core/ActionsModal/TabPanel.js
src/core/ActionsModal/index.js
src/core/Card/Actions.js
src/core/Card/Button.js
src/core/Card/index.js
stories/card.stories.js

Introduce Actions modal to handle share/embed/download on Cards.

Lights, Camera, Action!

---

src/core/BulletChart/BulletBar.js
src/core/BulletChart/index.js
src/core/LineChart.js
src/core/WrapLabel/index.js
src/core/propTypes.js
src/core/styles/createVictoryTheme.js
src/factory/ChartFactory.js
stories/chart.stories.js
stories/factory.stories.js

Add Bullet and Line Charts to ChartFactory.

Bullet and Line Charts

---

src/core/Card/index.js

https://github.com/CodeForAfrica/HURUmap-UI/pull/101#issuecomment-577663235

Fit any image in card to max 100% width

---

src/cms/attributes.js
src/cms/index.js

Ability to get deprecated data props

[Hotfix] Fix data attribute props and add ability to get the deprecated props

---

package.json
src/components/Card/HURUmapChart.js
src/components/Card/index.js
src/core/DataTable/exportCSV.js
src/core/DataTable/index.js
src/core/InsightContainer/Action/index.js
src/core/InsightContainer/index.js
src/factory/ChartFactory.js
stories/card.stories.js

- Adds show data
- Removes the need for them width definition
- Line charts are always vertical

Show me the money  🙌... i mean the data 

---

src/core/InsightContainer/index.js
src/factory/ChartFactory.js

Hide show more button when the full chart can he visible

Peek A Boo, I see you 👀 Fix Hide Show More button if chart fits

---

src/factory/ChartFactory.js

- Grouped chart data for line charts
Fixes #[171102401](https://www.pivotaltracker.com/story/show/171102401)

Group data for line charts when defined

---

package.json
src/core/PDFDataContainer.js
yarn.lock

Mike cousins has some buggy dependencies.

Use react-pdf instead of @mikecousins/react-pdf

---

src/cms/attributes.js
src/cms/index.js
src/components/Card/index.js

- User innerHTML as html widget source
- Update indicator to use blockId

Use innerHTML for html source

---

package.json
src/core/PDFDataContainer.js
stories/pdfcontainer.stories.js
yarn.lock

- Add PDF Container to stories
- Revert back to mikecousins pdf renderer

[Hotfix] Pdf stories + bug

---

packages/core/src/ActionsModal/DownloadPanel.js
packages/core/src/ActionsModal/EmbedPanel.js
packages/core/src/ActionsModal/SharePanel.js
packages/core/src/ActionsModal/index.js

Snippet Dialog

---

packages/charts/src/ChartFactory.js
packages/charts/src/WrapLabel/wrapSVGText.js

Fixes chart issues with wrong data values.

Ensure data value x is always a number

---

babel.config.js

Resolve modules from production and development

---

packages/charts/src/BarChart/index.js
packages/charts/src/ChartFactory.js
packages/charts/src/Legend.js
packages/charts/src/LegendLabel.js
packages/charts/src/LegendPoint.js
packages/charts/src/LineChart.js
packages/charts/src/PieChart/index.js
packages/charts/src/styles/createVictoryTheme.js
packages/charts/src/utils.js
stories/theme.js

Ensure legend is responsive within bounds.

Legendary - Responsive legend! 

---

packages/core/src/Card/index.js
packages/core/src/Snippet/index.js

Snippets to use correct id when sharing.

HOTFIX sharing snippets

---

packages/core/src/ChartContainer.js
packages/core/src/GroupActionsDropDown.js

- Pass embed class props to groupactiondownload

[HotFix] Embed Dropdown class props

---

packages/core/src/MapIt/index.js
packages/core/src/useGeoIndexLoader/buildGeoIndexQuery.js
packages/core/src/useGeoIndexLoader/index.js
packages/core/src/useProfileLoader/index.js
stories/mapit.stories.js

- Add score attribute to geo index loader hook
- Add vulnerability label and score on geography tooltio
Fixes [#172932081](https://www.pivotaltracker.com/story/show/172932081)

Vulnerability score on map Tooltip

---

packages/core/src/GroupActionsDropDown.js
packages/core/src/ShareDropDown.js

window should only be access via guard for SSR
N/A
- x ] I have performed a self-review of my own code

[HotFix] Typecheck window for SSR

---

package.json
packages/core/src/ChartContainer.js
packages/core/src/InsightContainer/index.js
stories/container.stories.js
yarn.lock

Configurable Attribution Source

---

packages/core/src/Snippet/index.js
yarn.lock

We need to make sure only a single `indicatorId` is set on seach params, otherwise we end up with multiple indicatorIds where only the first one takes precedence.
N/A

[HotFix] searchParams indicatorId

---

packages/core/src/MapIt/index.js

Set map's view to the `center` & `zoom` if provided

[Hotfix] Map zoom and center state

---

packages/charts/src/ChartFactory.js

Either show defined description or field label

Number chart description

---

packages/charts/src/ChartFactory.js
packages/core/package.json
stories/chart.stories.js
stories/theme.js

- Deepmerge parts properties for line charts

Line Chart parts props

---

packages/charts/src/ChartFactory.js

- Process line charts data to always have numbers for y values
- Include referenceData for line charts in ChartFactory

Line charts y values

---

packages/charts/src/ChartFactory.js
packages/core/src/Card/HURUmapChart.js

- Fix processedData array.push for line charts
- Bug referenceData on hurumap card if defined

[HotFix] Processed data array push

---

packages/charts/src/ChartFactory.js
packages/charts/src/LineChart.js
packages/core/src/Card/HURUmapChart.js
stories/theme.js

- Multiple strokeWidth
- Fix label for primary data when we are comparing, or showing reference
- Fix grouped line chart

Fix line label

---

packages/charts/src/ChartFactory.js
packages/charts/src/LineChart.js
stories/theme.js

- Deep merge takes only two parameters
- Fix parts  props from chartProps overrides the merged parts

[Hotfix] Fix deep merge + parts

---

packages/core/src/ChartContainer.js
packages/core/src/GroupActionsDropDown.js
packages/core/src/MapIt/index.js
stories/mapit.stories.js

- Allow zoomControl position to be customisable
- Fix spelling mistake on class props

[Hotfix] Custom map zoom control position & social icons classes

---

yarn.lock

Upgrade all backward compatible dependencies
N/A

[Hotfix] Upgrade Dependencies
