CodeForAfrica/HURUmap-UI

- src/NestedProportionalAreaChart/ScaledCircle.js
- src/PieChart/index.js
- src/styles/createVictoryTheme.js
- stories/chart.stories.js
Set `donut` as the default pie chart mode.
> Donut as the default Pie chart mode

- package.json
- src/A.js
- src/BlockLoader.js
- src/ChartContainer/index.js
- src/ContentLoader.js
- src/MapIt/index.js
- src/Theme.js
- src/TypographyLoader.js
- src/index.js
- stories/Theme.js
- stories/common.js
- stories/container.stories.js
- yarn.lock
Video: https://recordit.co/8XI1wzJpDo
The gif below lost quality, not good representation.
> Map loader + Chart loader + sourceLink on chart container

- src/Label.js
- src/PieChart/LegendLabel.js
- src/PieChart/PieLabel.js
- src/PieChart/index.js
- stories/chart.stories.js
While very capable, `VictoryLabel` doesn't support text wrapping. This PR adds a custom `Label` component built on top of `VictoryLabel` that wraps text _before_ passing it to `VictoryLabel`.
> Add text wrapping to VictoryLabel & Use it for Legend

- .bumpversion.cfg
- package.json
- src/BarChart/BarLabel.js
- src/BlockLoader.js
- src/ChartContainer/index.js
- src/ContentLoader.js
- src/InsightContainer/index.js
- src/MapIt/index.js
- src/WrapLabel/index.js
- yarn.lock
The skeleton loader is and svg which requires pixel values.
This PR ensure px values are used since chrome is strict and was breaking.
Issue:
> Fix SVG Blockloader Breaking in Chrome

- package.json
- src/InsightContainer/index.js
- yarn.lock
+ [x] add `toPng` using `dom-to-image`: Screenshot Chart + Enable processing of `dataUrl`,
+ [x] Add default download handler, and
+ [x] Pass `dataUrl` to `handleDownload` and `handleShare` functions if provide.
> Improve Insight Chart Container Download/Share Actions

- src/core/BarChart/index.js
- src/core/BulletChart/BulletBar.js
- src/core/BulletChart/index.js
- src/core/ComparisonBarChart.js
- src/core/LineChart.js
- src/core/NestedProportionalAreaChart/HorizontalLegend.js
- src/core/NestedProportionalAreaChart/ScaledCircle.js
- src/core/NestedProportionalAreaChart/ScaledSquare.js
- src/core/NestedProportionalAreaChart/VerticalLegend.js
- src/core/NestedProportionalAreaChart/index.js
- src/core/PieChart/SharedEvents.js
- src/core/PieChart/index.js
- src/core/styles/createVictoryTheme.js
- stories/chart.stories.js
Add tooltips to charts that mainly use [Primitive/Simple](https://formidable.com/open-source/victory/docs/victory-primitives) Victory components.
> ... And then there were none

- src/factory/useProfileLoader/queries.js
This feature helps resolve PT issue https://www.pivotaltracker.com/story/show/169501050
When querying for population, allow the table to be queried with conditions example:
```
// Getting latest population
[
'allTotalPopulation',
{
orderBy: 'TOTAL_POPULATION_YEAR_DESC',
first: 1
}
]
```
or 
```
// Getting population of year 2017
[
'allTotalPopulation',
{
condition:  { totalPopulationYear: '2017' }
}
]
```
> Allow population table conditions for fetching

- src/factory/useProfileLoader/index.js
We were using the the `parent.parentLevel` and  `parent.parentGeoCode` instead of `parent.geoLevel` and `parent.geoCode`.
Problem discovered here https://github.com/CodeForAfrica/Dominion.AFRICA/pull/51 
> Hotfix useProfileLoader using wrong parent level and geo code details

- src/core/BarChart/index.js
- src/core/ChartContainer/index.js
- src/factory/ChartFactory.js
- stories/container.stories.js
- stories/factory.stories.js
Solution: 
Pass the props as `<ChartFactory ... {...chart.visual.props} />`
Problem:
In `charts.json`, each **visual** has a `props` attribute where one can specify all chart customization they need. For example:
```
...
props: {
parts: {
legend: {
size: 100,
}
},
offset: 20,
}
....
```
> Accept visual definition props

- src/core/ChartContainer/index.js
- src/core/InsightContainer/index.js
Chart containers break if source is undefined
> [Hotfix] Chart container source could be "undefined"

- src/core/InsightContainer/Action/index.js
- src/core/InsightContainer/index.js
- stories/container.stories.js
Default:
Customization:
We need this behaviour to support Florish charts on the front-end since they don't have actions like `Show Data` or `Compare`.
> [Hotfix] Default InsightChartContainer actions & their customizability

- src/core/InsightContainer/Insight.js
- stories/container.stories.js
Analysis link title on insight container does not update to the custom prop sent. This PR fixes that
> [Bug] Fix analysis link title prop

- src/core/InsightContainer/index.js
- src/core/utils.js
- stories/container.stories.js
Ignore the script elements for dom to image since they sometimes cause errors. Dom to image does not need scripts so it is safe to ignore.
Test setting:
```
iframeSrc: http://localhost:8080/wp-json/hurumap-data/flourish/RqiI1akD/
documentDomain: localhost
```
> Fix iframe downloads

- src/core/ActionButton.js
- src/core/BarChart/BarLabel.js
- src/core/BulletChart/BulletBar.js
- src/core/BulletChart/index.js
- src/core/ComparisonBarChart.js
- src/core/EmbedDropDown.js
- src/core/Label.js
- src/core/LegendLabel.js
- src/core/NestedProportionalAreaChart/ScaledCircle.js
- src/core/NestedProportionalAreaChart/ScaledSquare.js
- src/core/PieChart/DonutTooltip.js
- src/core/PieChart/index.js
- src/core/ShareDropDown.js
- src/core/utils.js
- src/factory/ChartFactory.js
- src/factory/utils/aggregateData.js
- stories/chart.stories.js
- stories/container.stories.js
- stories/factory.stories.js
- stories/mapit.stories.js
`2019\n10000` (Optional, if not provided, the `label` above will be used),
> Standardize Tooltips + Fix some warnings

- src/factory/ChartFactory.js
Use `x` for data point label; not `label`.
N/A
> [Hotfix] Nested Area Data Label

- src/factory/ChartFactory.js
- src/factory/utils/aggregateData.js
- stories/factory.stories.js
> Of ChartFactory & Percent

- src/factory/ChartFactory.js
Prioritize profile `label` for `NestedProportionalAreaChart` labels.
N/A
> [Hotfix] Prioritise profile label for Nested Area Chart labels

- src/factory/ChartFactory.js
- stories/factory.stories.js
If  `id` is provided as part of chart definition, ChartFactory should include it in the final `div`. This will help us link to a given chart directly from search results, social media sharing, etc.
> [Hotfix] chart `id` in ChartFactory

- src/factory/ChartFactory.js
Theme props on chartfactory has a wrong proptypes.
> [Hotfix] Theme proptypes on chartfactory

- src/core/ChartContainer.js
- src/core/EmbedDropDown.js
- src/core/ShareDropDown.js
- stories/container.stories.js
`ChartContainer` needs to support `variant` (similar to how `InsightContainer`) for it to be useful in profile pages as well as normal content pages, for example as **Featured Data** on project homepage.
> ChartContainer variant support

- src/factory/ChartFactory.js
Include padding in size calculations
> [Hotfix] ChartFactory BarChart padding

- src/components/utils/index.js
Old `id` was being used on `url.searchParam` instead of the `indicatorId` which may include `geoId` if present.
N/A
> [Hotfix] Use indicatorId on searchParam

- src/core/PieChart/index.js
- stories/chart.stories.js
> [HotFix] PieChart donut label data selection

- src/core/BarChart/index.js
- src/core/WrapLabel/index.js
- src/core/WrapLabel/wrapSVGText.js
Split computation of max label dimension to avoid many hooks being invoked
> Split computation of max label dimension to avoid many hooks being invoked

- packages/content/src/dataProps.js
On production, Indicator widget type is undefined. Missing from attributes
Also, hurumap card while trying to fix this [issue](https://github.com/TakwimuAfrica/Dashboard/pull/71) I get,
> Fix undefined Indicator type

- packages/charts/src/BarChart/index.js
- packages/charts/src/ChartFactory.js
- packages/charts/src/WrapLabel/wrapSVGText.js
- stories/container.stories.js
- stories/factory.stories.js
- Group charts truncate group columns first then truncate groups
- Use math instead of for loops
Resolves #123
> Math Is In Session -  Fix show more and show less data calculations

- lerna.json
- package.json
- packages/charts/package.json
- packages/content/package.json
- packages/core/package.json
- yarn.lock
Improve `lerna` setup to reuse much of `yarn workspaces` as possible as well as standardize what we define as `peerDependencies`
- "@material-ui/core",
- "@material-ui/icons",
- "apollo-client",
- "apollo-utilities",
- "graphql",
- "graphql-tag,
- "lodash",
- "react", and
- "react-dom".
--------------------
`*` Needs testing
It's best to revert back to prelease versioning for the next release `0.3.5` to give ourselves time to do all these small fixes and optimization.
N/A
> Chore/lerna + yarn workspace

- packages/core/src/Snippet/Actions.js
- packages/core/src/Snippet/index.js
- stories/snippet.stories.js
Current Snippet title uses the same font as text and doesn't accommodate long titles very well
> Snippet Title

- packages/charts/src/BarChart/index.js
- packages/charts/src/ChartFactory.js
- packages/charts/src/WrapLabel/wrapSVGText.js
- stories/card.stories.js
- stories/container.stories.js
- stories/theme.js
- Use the correct label dimension for the corresponding padding
- Use the the barWidth to find the amount of bars that  can fit a chart instead of the offset
Test with:
graphql -> https://graphql.hurumap.org/graphql
definition -> 
```
{
"id": 668,
"title": "Contribution by principal donor",
"subtitle": "Development Assistance",
"visual": {
"type": "column",
"table": "allGlobalHealthSecurityIndices",
"x": "category",
"y": "score",
"typeProps": {
"horizontal": false
},
"queryAlias": "v668"
},
"stat": {
"type": "number",
"subtitle": "Development Assistance",
"description": "Donor Contribution",
"unique": false,
"aggregate": "sum",
"queryAlias": "v668"
},
"source": [],
"description": []
}
```
> Fix use correct label dimmension for padding

- packages/charts/src/BarChart/index.js
- packages/charts/src/ChartFactory.js
- packages/charts/src/LegendLabel.js
- packages/charts/src/LineChart.js
- packages/charts/src/PieChart/DonutTooltip.js
- packages/charts/src/PieChart/index.js
- packages/charts/src/WrapLabel/wrapSVGText.js
- packages/charts/src/styles/createVictoryTheme.js
- packages/charts/src/utils.js
- stories/chart.stories.js
- stories/factory.stories.js
Enables legend by default for grouped data based charts (`Bar` and `Line`). It also updates the `ChartFactory` to respect label or tooltip when present in a data point instead of always creating new ones
`donutLabelRadiusRatio` is also introduced as `Pie` chart theme option to control how much of donut radius is used by label. Currently, all of it (`1.0`) was being used causing issues when labels was broken down into multiple lines i.e. lines at the top should not use the whole radius since a circle is not as wide near the top as in the middle.
Delivers #172160825
> Grouped Data Legend

- packages/core/src/PDFDataContainer.js
It is crucial for performance to use PDF.js worker whenever possible. This ensures that PDF files will be rendered in a separate thread without affecting page performance.
This PR adds external `pdf.worker.js`.
Fixes ##172242441
> [Hotfix] Enable PDF.js worker

- packages/core/src/useGeoIndexLoader/index.js
`countryCode` was being passed instead of `scoreField`. This PR fixes that.
N/A
> [HotFix] Wrong scoreField in buildGeoIndexQuery

- packages/charts/src/ChartFactory.js
- packages/charts/src/NumberVisuals.js
`ChartFactory` should check if `description` has a value before including it `NumberVisuals` description field since `${descrption}` = `"undefined"` if description is `undefined`
N/A
> [HotFix] ChartFactory NumberVisuals description
